version: '3.8'

name: efp-api

networks:
  default:
    driver: bridge

services:
  ping:
    container_name: api-ping
    image: bash:latest
    build:
      dockerfile_inline: |
        FROM bash:latest
        WORKDIR /usr/src/app
        RUN apk add --no-cache curl && rm -rf /var/cache/apk/*
        COPY ./scripts/ping.sh /usr/src/app/ping.sh
    command: ./ping.sh
    entrypoint: /usr/local/bin/bash
    networks:
      - default

  api:
    container_name: api-dev
    build:
      context: .
      dockerfile: Dockerfile
    command: >
          bun --hot --watch ./src/index.ts
    tty: true
    stdin_open: true
    expose:
      - 8787
    ports:
      - 8787:8787/tcp
    networks:
      - default
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@efp-database:5432/efp?sslmode=disable}
