#: schema https://github.com/cloudflare/workers-sdk/files/12887590/wrangler.schema.json
# https://developers.cloudflare.com/workers/wrangler/configuration

# default stage is "development"

#
# start of globally inheritable configuration
name = "indexer"
main = "./src/index.ts"
minify = true
keep_vars = true
node_compat = true
placement = { mode = "smart" }
compatibility_date = "2023-10-30"
# end of globally inheritable configuration
#
vars = { ENVIRONMENT = "development" }
services = [{ binding = "ens", service = "ens" }]

[env.development]
name = "development"
workers_dev = true
vars = { ENVIRONMENT = "development", IS_DEMO = "false"  }
routes = [
  { pattern = "development.api.ethfollow.xyz", custom_domain = true, zone_id = "0bb17a76c05f664a7c6cfd16721216cf" },
]
services = [{ binding = "ens", service = "ens" }]

[env.production]
name = "production"
workers_dev = true
vars = { ENVIRONMENT = "production", IS_DEMO = "false" }
routes = [
  { pattern = "api.ethfollow.xyz", custom_domain = true, zone_id = "0bb17a76c05f664a7c6cfd16721216cf" },
  { pattern = "production.api.ethfollow.xyz", custom_domain = true, zone_id = "0bb17a76c05f664a7c6cfd16721216cf" },
]
services = [{ binding = "ens", service = "ens" }]
kv_namespaces = [
  { binding = "EFP_DEMO_KV", id = "c490de9b7d434fdb927933a86d1d2db4" },
]
