name = "indexer"
main = "./src/index.ts"
keep_vars = true
node_compat = true
compatibility_date = "2023-10-30"

[placement]
mode = "smart"

[[services]]
binding = "ens"
service = "ens"

[env.production]
ENV = "production"

[env.development]
ENV = "development"
