#: schema https://github.com/cloudflare/workers-sdk/files/12887590/wrangler.schema.json
# https://developers.cloudflare.com/workers/wrangler/configuration

# default stage is "development"

# 
# start of globally inheritable configuration
name = "indexer"
main = "./src/index.ts"
# route = "api.ethfollow.xyz/*"
minify = true
keep_vars = true
node_compat = true
placement = { mode = "smart" }
compatibility_date = "2023-10-30"
# end of globally inheritable configuration
#
vars = { ENVIRONMENT = "development" }
services = [{ binding = "ens", service = "ens" }]
# kv_namespaces = [
#   { binding = "EFP_DEMO_KV", id = "b662b0a7236c4145888a7d700076e43b" },
# ]

[env.development]
name = "development"
workers_dev = true
vars = { ENVIRONMENT = "development" }
routes = [
  { pattern = "development.api.ethfollow.xyz", custom_domain = true, zone_id = "8db41cc2c22fe00c6a852388bdea1e5f" },
]
services = [{ binding = "ens", service = "ens" }]
# kv_namespaces = [
#   { binding = "EFP_DEMO_KV", id = "b662b0a7236c4145888a7d700076e43b" },
# ]

[env.production]
name = "production"
workers_dev = true
vars = { ENVIRONMENT = "production", IS_DEMO = "true" }
routes = [
  { pattern = "api.ethfollow.xyz", custom_domain = true, zone_id = "8db41cc2c22fe00c6a852388bdea1e5f" },
  { pattern = "production.api.ethfollow.xyz", custom_domain = true, zone_id = "8db41cc2c22fe00c6a852388bdea1e5f" },
]
services = [{ binding = "ens", service = "ens" }]
kv_namespaces = [
  { binding = "EFP_DEMO_KV", id = "b662b0a7236c4145888a7d700076e43b" },
]
