name: Checks

on:
  pull_request:
  # allow workflow to be called from other workflows
  workflow_call:
  # allow workflow to be called from github.com UI
  workflow_dispatch:
  push:
    branches-ignore: [develop]

concurrency:
  group: checks-${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  NODE_OPTIONS: '--no-warnings'
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    name: '🔎 Checks'
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: '🔑 Checkout'
        uses: actions/checkout@v4.1.1

      - name: '🐰 Setup Bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: 'Setup Biome'
        uses: biomejs/setup-biome@v1
        with:
          version: 'latest'

      # if lint fails no need to continue
      - name: '🧹 Lint'
        continue-on-error: false
        run: biome ci .

      - name: '📦 Install Dependencies'
        run: bun install --frozen-lockfile

      - name: '🧪 Typecheck'
        continue-on-error: true # temp
        run: bunx tsc --project tsconfig.json --noEmit

      - name: '🔧 Build'
        run: bun run build

      - name: '🧪 Test'
        # TODO: remove this once all paths are testing-ready
        continue-on-error: true
        env:
          API_URL: http://localhost:8787/api/v1
          IS_DEMO: true
          VERBOSE: true
        run: |
          bunx wrangler dev --latest=true &
          sleep 3
          /bin/bash ./tests/endpoints.sh
