name: Deploy

on:
  workflow_dispatch:
    inputs:
      WORKERS_ENVIRONMENT:
        type: choice
        description: 'Cloudflare Workers Environment to deploy to'
        required: false
        options:
          - 'development'
          - 'production'
          - 'all'
        default: 'development'

  push:
    branches: [develop]

concurrency:
  group: deploy-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true
  NODE_OPTIONS: '--no-warnings'
  WORKERS_ENVIRONMENT: ${{ github.event.inputs.WORKERS_ENVIRONMENT }}

jobs:
  checks:
    uses: './.github/workflows/checks.yml'

  deploy-workers:
    if: ${{ !contains(github.event.head_commit.message, '[skip-deploy]') }}
    needs: [checks]
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      # Supabase database url
      DEVELOPMENT_DATABASE: ${{ secrets.DATABASE_URL }}
      PRODUCTION_DATABASE: null
    steps:
      - name: '🔑 Checkout'
        uses: actions/checkout@v4.1.1

      - name: '🐰 Setup Bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: 'Install Dependencies'
        run: bun install

      - name: 'Get Commit SHA'
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

        # https://developers.cloudflare.com/workers/wrangler/commands/#deploy
      - name: '[development] Deploy Cloudflare Workers 🔶'
        if: |
          ${{ contains(env.WORKERS_ENVIRONMENT, 'development') || 
              contains(env.WORKERS_ENVIRONMENT, 'all') ||
              contains(github.event.head_commit.message, '[development]') || 
              contains(github.event.head_commit.message, '[all]') }}
        run: |
          echo ${{ env.DEVELOPMENT_DATABASE }} | bunx wrangler@latest secret put DATABASE_URL --config=wrangler.toml --env=development

          bunx wrangler@latest deploy ./src/index.ts \
            --env=development \
            --minify=true \
            --latest=true \
            --keep-vars=true \
            --node-compat=true \
            --config=wrangler.toml \
            --compatibility-date=2023-10-30 \
            --var ENVIRONMENT:"development" \
            --var COMMIT_SHA:"$COMMIT_SHA"

        # https://developers.cloudflare.com/workers/wrangler/commands/#deploy
      - name: '[production] Deploy Cloudflare Workers 🔶'
        if: |
          ${{ contains(env.WORKERS_ENVIRONMENT, 'production') || 
              contains(env.WORKERS_ENVIRONMENT, 'all') || 
              contains(github.event.head_commit.message, '[production]') || 
              contains(github.event.head_commit.message, '[all]') }}
        run: |
          # echo ${{ env.PRODUCTION_DATABASE }} | bunx wrangler@latest secret put DATABASE_URL --config=wrangler.toml --env=production

          bunx wrangler@latest deploy ./src/index.ts \
            --env=production \
            --minify=true \
            --latest=true \
            --keep-vars=true \
            --node-compat=true \
            --config=wrangler.toml \
            --compatibility-date=2023-10-30 \
            --var ENVIRONMENT:"production" \
            --var COMMIT_SHA:"$COMMIT_SHA"
